Bump JRuby due to setup-ruby not liking it
```
Error: Error: Unavailable version 9.3.10.0 for jruby on ubuntu-24.04
          You can request it at https://github.com/ruby/setup-ruby/issues
          Cause: Unexpected HTTP response: 404
```